/**
 * Static-demo data client.
 * Implements the exact same functions as ./apiDataClient.js, but reads from the JSON
 * fixtures in frontend/public/demo-data/ (generated by the backend's DemoExportService,
 * see /api/export-demo) instead of calling a live backend. Everything - filtering, sorting,
 * pagination, grouping offers by store, analytics aggregates, search - is derived client-side
 * from those fixtures, so this works fully standalone (e.g. deployed to Vercel with no
 * backend at all).
 */

const DEMO_DATA_BASE = '/demo-data';

let phonesPromise = null;
let priceHistoryPromise = null;

const loadPhones = () => {
  if (!phonesPromise) {
    phonesPromise = fetch(`${DEMO_DATA_BASE}/phones.json`).then((response) => {
      if (!response.ok) {
        throw new Error(`Failed to load demo phones data: ${response.status}`);
      }
      return response.json();
    });
  }
  return phonesPromise;
};

const loadPriceHistory = () => {
  if (!priceHistoryPromise) {
    priceHistoryPromise = fetch(`${DEMO_DATA_BASE}/price-history.json`).then((response) => {
      if (!response.ok) {
        throw new Error(`Failed to load demo price history data: ${response.status}`);
      }
      return response.json();
    });
  }
  return priceHistoryPromise;
};

const groupBy = (items, key) => {
  const map = new Map();
  for (const item of items) {
    const value = item[key];
    if (value == null) continue;
    if (!map.has(value)) map.set(value, []);
    map.get(value).push(item);
  }
  return map;
};

const matchesFilters = (phone, filters) => {
  const { search, brands, sources, colors, storage, ram, minPrice, maxPrice } = filters;

  if (search) {
    const term = search.toLowerCase();
    const haystack = `${phone.title ?? ''} ${phone.rawTitle ?? ''}`.toLowerCase();
    if (!haystack.includes(term)) return false;
  }
  if (brands?.length && !brands.includes(phone.brand)) return false;
  if (sources?.length && !sources.includes(phone.source)) return false;
  if (colors?.length && !colors.includes(phone.colorCanonical)) return false;
  if (storage?.length && !storage.includes(phone.storageGb)) return false;
  if (ram?.length && !ram.includes(phone.ramGb)) return false;
  if (minPrice && phone.price < Number(minPrice)) return false;
  if (maxPrice && phone.price > Number(maxPrice)) return false;
  return true;
};

const sortPhones = (phones, sort) => {
  if (!sort) return phones;
  const [field, direction] = sort.split(',');
  const dir = direction === 'desc' ? -1 : 1;

  return [...phones].sort((a, b) => {
    const av = a[field];
    const bv = b[field];
    if (av == null || bv == null) return 0;
    const cmp = av < bv ? -1 : av > bv ? 1 : 0;
    return cmp * dir;
  });
};

export const fetchPhones = async (page = 0, size = 20, filters = {}) => {
  const all = await loadPhones();
  const filtered = all.filter((phone) => matchesFilters(phone, filters));
  const sorted = sortPhones(filtered, filters.sort);

  const start = page * size;
  const content = sorted.slice(start, start + size);
  const totalElements = filtered.length;
  const totalPages = Math.max(1, Math.ceil(totalElements / size));

  return {
    content,
    totalElements,
    totalPages,
    number: page,
    size,
    first: page === 0,
    last: page >= totalPages - 1,
    empty: content.length === 0,
  };
};

const uniqueSorted = async (key) => {
  const all = await loadPhones();
  return [...new Set(all.map((phone) => phone[key]).filter((value) => value != null))].sort();
};

const uniqueSortedNumeric = async (key) => {
  const all = await loadPhones();
  return [...new Set(all.map((phone) => phone[key]).filter((value) => value != null))].sort(
    (a, b) => a - b,
  );
};

export const fetchBrands = () => uniqueSorted('brand');
export const fetchSources = () => uniqueSorted('source');
export const fetchColors = () => uniqueSorted('colorCanonical');
export const fetchStorageOptions = () => uniqueSortedNumeric('storageGb');
export const fetchRamOptions = () => uniqueSortedNumeric('ramGb');

export const fetchProductOffers = async (id) => {
  const all = await loadPhones();
  const numericId = Number(id);
  const base = all.find((phone) => phone.id === numericId);
  if (!base) return [];

  const sameModel = all.filter((phone) => phone.phoneModelId === base.phoneModelId);
  const bySource = groupBy(sameModel, 'source');

  return [...bySource.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([source, offers]) => {
      const prices = offers.map((offer) => offer.price);
      const availableColors = [
        ...new Set(offers.map((offer) => offer.colorCanonical).filter(Boolean)),
      ].sort();
      const colors = [...offers]
        .sort((a, b) => a.price - b.price)
        .map((offer) => ({
          offerId: offer.id,
          colorRaw: offer.colorRaw,
          colorCanonical: offer.colorCanonical,
          price: offer.price,
          siteLink: offer.siteLink,
          imageUrl: offer.imageUrl,
        }));

      return {
        phoneModelId: base.phoneModelId,
        brand: base.brand,
        title: base.title,
        source,
        minPrice: Math.min(...prices),
        maxPrice: Math.max(...prices),
        availableColors,
        colors,
      };
    });
};

export const fetchPriceHistory = async (phoneModelId) => {
  const data = await loadPriceHistory();
  return data.history?.[String(phoneModelId)] ?? [];
};

export const fetchAveragePriceByBrand = async () => {
  const all = await loadPhones();
  const byBrand = groupBy(all, 'brand');
  return [...byBrand.entries()]
    .map(([brand, items]) => ({
      brand,
      averagePrice: Math.round(items.reduce((sum, item) => sum + item.price, 0) / items.length),
    }))
    .sort((a, b) => a.brand.localeCompare(b.brand));
};

export const fetchListingsPerSource = async () => {
  const all = await loadPhones();
  const bySource = groupBy(all, 'source');
  return [...bySource.entries()]
    .map(([source, items]) => ({ source, count: items.length }))
    .sort((a, b) => a.source.localeCompare(b.source));
};

export const fetchPriceComparison = async (normalizedTitle) => {
  const all = await loadPhones();
  return all
    .filter((phone) => phone.modelKey === normalizedTitle)
    .sort((a, b) => a.source.localeCompare(b.source))
    .map((phone) => ({ source: phone.source, price: phone.price }));
};

export const fetchCheapestPerBrand = async () => {
  const all = await loadPhones();
  const byBrand = groupBy(all, 'brand');
  const result = {};
  for (const [brand, items] of byBrand) {
    const cheapest = items.reduce((min, item) => (item.price < min.price ? item : min));
    result[brand] = {
      id: cheapest.id,
      brand,
      title: cheapest.title,
      price: cheapest.price,
      imageUrl: cheapest.imageUrl,
      source: cheapest.source,
      siteLink: cheapest.siteLink,
    };
  }
  return result;
};

const PRICE_BUCKETS = [
  { range: '0-10k', min: 0, max: 10000 },
  { range: '10k-20k', min: 10000, max: 20000 },
  { range: '20k-30k', min: 20000, max: 30000 },
  { range: '30k+', min: 30000, max: Infinity },
];

export const fetchPriceDistribution = async () => {
  const all = await loadPhones();
  return PRICE_BUCKETS.map((bucket) => ({
    range: bucket.range,
    count: all.filter((phone) => phone.price >= bucket.min && phone.price < bucket.max).length,
  })).filter((bucket) => bucket.count > 0);
};

export const searchPhones = async (query) => {
  const all = await loadPhones();
  const term = query.toLowerCase();
  const seenModelKeys = new Set();
  const results = [];

  for (const phone of all) {
    if (seenModelKeys.has(phone.modelKey)) continue;
    if (phone.title?.toLowerCase().includes(term)) {
      seenModelKeys.add(phone.modelKey);
      results.push({ title: phone.title, normalizedTitle: phone.modelKey });
    }
  }
  return results;
};
