spring.application.name=phone-aggregator

spring.datasource.url=jdbc:postgresql://localhost:5438/phone_aggregator_db
spring.datasource.username=phone_aggregator_user
spring.datasource.password=phone_aggregator_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8083